### ISSUE TITLE
Suggestions for using purge css?

### ISSUE THREAD

**Issue by beamercola** [talensjr/gatsby-theme-tailwindcss#3]
Personally i feel like it should be embedded in the theme, since nobody should be using tailwind without purge

**Comment by talensjr** [comment]
Hi @beamercola, my intention with this theme is to be the least opinionated as possible, so by now I will include in the docs how to use it. Thanks for the suggestion.

**Comment by talensjr** [comment]
@beamercola it is done, I will close the issue, but feel free to reopen it if you want to  add something that is missing.
